accounts/urls.py
from django.contrib import admin
from django.urls import path

from . views import (
    login_user,
    logout_user,

    about,
    contact,
    adminList,

    signup,
    activate
    )
app_name = "accounts"

urlpatterns = [
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),

    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('adminList/', adminList, name="adminList"),

     path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),

] 

assignment/urls.py
from django.contrib import admin
from django.urls import path
from django_downloadview import ObjectDownloadView
from . views import (
	index,
    addAssignment,
    updateAssignment,
    deleteAssignment,

    userAssignments,
    adminAssignments,

    accept,
    completed,
    counter,
    services,
    singleAssignment,

    assignmentChange,
    changes,
	)
from . models import UserAssignment, AssignmentMedia

download = ObjectDownloadView.as_view(model=UserAssignment, file_field='file')
downloadFinished = ObjectDownloadView.as_view(model=AssignmentMedia, file_field='file')
app_name = "assignment"

urlpatterns = [
    path('', index, name="index"),
    path('assignment/add/', addAssignment, name="addAssignment"),
    path('assignment/<int:assignment_id>/update/', updateAssignment, name="updateAssignment"),
    path('assignment/<int:assignment_id>/delete/', deleteAssignment, name="deleteAssignment"),

    path('assignments/', userAssignments, name="userAssignments"),
    path('assignments/admin/', adminAssignments, name="adminAssignments"),
    path('accept/<int:assignment_id>/', accept, name="accept"),
    path('completed/<int:assignment_id>/', completed, name="completed"),
    path('counter/', counter, name="counter"),

    path('services/', services, name="services"),
    path('assignment/<int:assignment_id>/', singleAssignment, name="singleAssignment"),

    path('assignment/change/', assignmentChange, name="assignmentChange"),
    path('changes/', changes, name="changes"),

    path('download/<int:pk>/', download, name="download_assignment"),
    path('downloadFinish/<int:pk>/', downloadFinished, name="downloadFinished"),
]

payment/urls.py
from django.contrib import admin
from django.urls import path

from . views import (
    payment_process,
    payment_done,
    payment_canceled,
    )
app_name = "payment"

urlpatterns = [
    path('payment_done/<int:assignmentId>/', payment_done, name="payment_done"),
    path('payment_canceled/<int:assignmentId>/', payment_canceled, name="payment_canceled"),
    path('payment_process/<int:assignment_id>/', payment_process, name="payment_process"),
   
] 

workvat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap

from assignment.sitemaps import StaticViewSitemap

sitemaps = {
    # 'product': ProductSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),

    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include("assignment.urls", namespace="assignment")),
    path('payment/', include("payment.urls", namespace="payment")),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change_form.html'), name="password_change"),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name="password_change_done"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),  name='password_reset_confirm'),
    path('password_reset_complete/', auth_views. PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

]

accounts/models.py
from django.db import models

from django.contrib.auth.models import User

from ckeditor.fields import RichTextField

class Testimonial(models.Model):
	user 		= models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	content		= RichTextField()

	timestamp 	= models.DateField(auto_now=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.views import View
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.core.mail import EmailMessage, send_mail
from django.contrib.auth.models import User


def signup(request):
    request.session["userAv"] = False
    if request.method == "POST":
        firstName = request.POST.get("firstName")
        lastName = request.POST.get("lastName")
        email = request.POST.get("email")
        userExist = User.objects.filter(email=email)
        if userExist.exists():
            request.session["userAv"] = True
        else:
            user = User(username=email, first_name=firstName, last_name=lastName, email=email)
            user.set_unusable_password()
            user.is_active = False
            user.save()

            # Send an email to the user with the token:
            mail_subject = 'Activate your account.'
            current_site = get_current_site(request)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = account_activation_token.make_token(user)
            activation_link = "{0}/accounts/activate/{1}/{2}".format("https://workvat.com", uid, token)
            message = "Hello {0},\n {1}".format(user.first_name, activation_link)
            to_email = email
            email = EmailMessage(mail_subject, message, 'info@workvat.com', to=[to_email])
            email.send()
            return render(request, './confirm_email.html')
    return redirect("assignment:index")

def activate(request, uidb64, token):
    if request.method == "POST":
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        if password == password2:
            user = request.user
            user.set_password(password)
            user.save()
            login(request, user)
            # update_session_auth_hash(request, user) # Important, to update the session with the new password
            return redirect("assignment:index")
        else:
            return render(request, 'activation.html')
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        # activate user and login:
        user.is_active = True
        user.save()
        login(request, user)

        # form = PasswordChangeForm(request.user)
        return render(request, 'activation.html')

    else:
        return HttpResponse('Activation link is invalid!')



def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        userIn = authenticate(username=username, password=password)
        if userIn:
            login(request, userIn)
            next_endpoint = request.GET.get("next")
            return redirect("/")
    return render(request, './login.html')


def logout_user(request):
    logout(request)
    return redirect("/")

def contact(request):
    template_name = "./contact.html"
    send = False
    if request.method == "POST":
        user = request.user
        if user.is_authenticated:
            firstName = user.first_name
            lastName = user.last_name
            email = user.email
        else:
            firstName = request.POST.get("firstName")
            lastName = request.POST.get("lastName")
            email = request.POST.get("email")
        message = request.POST.get("message")
        mail_subject = request.POST.get("subject")
        message = "Customer Name: {} {}\nCustomer Email : {} \n Message {}".format(firstName, lastName, email, message)
        to_email = email
        email = EmailMessage(mail_subject, message, to=['info@workvat.com'])
        email.send()
        # send_mail(mail_subject, message, email, ['hashimathman@gmail.com'], fail_silently=False,)
        send = True
    context = {'send':send}
    return render(request, template_name, context)

def about(request):
    template_name = "./about.html"
    return render(request, template_name)

@login_required
def adminList(request):
    template_name = "./adminList.html"
    return render(request, template_name)

accounts/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  | About us
{% endblock %}
{% block description %}
      <meta name="description" content="About us workvat">
{% endblock %}
{% block front %}
	 <div class="mb-5 text-center">
      <h1 class="text-white font-weight-bold">About Us</h1>
      <!-- <p>Find your dream jobs in our powerful career website template.</p> -->
    </div>
{% endblock%}

{% block content %}
	<section class="site-section pb-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a data-fancybox data-ratio="2" href="https://www.youtube.com/watch?v=CCX0mMaEEKc" class="block__96788">
              <span class="play-icon"><span class="icon-play"></span></span>
              <img src="{% static 'images/workvat.jpg' %}" alt="Image" class="img-fluid img-shadow">
            </a>
          </div>
          <div class="col-lg-5 ml-auto">
            <h2 class="section-title mb-3">About Workvat</h2>
            <!-- <p class="lead">Eveniet voluptatibus voluptates suscipit minima, cum voluptatum ut dolor, sed facere corporis
              qui, ea quisquam quis odit minus nulla vitae. Sit, voluptatem.</p> -->
            <p>Workvat is an online freelance  website with experienced online freelance workers with over ten years’ experience in Delivery of ; Assignments , all types of Essays, article review, course work , business plan ,presentation or speech ,term paper, dissertation ,websites  applications and software computer projects, Projects Essays, Thesis Papers, Dissertations, publications and other academic works. Students and Writers communicate directly, without intermediaries, and we work with the student range which shouldn’t fall below our marked price range. We deal with all academic disciplines making it easier for all students to enjoy our services globally. Our working principle as WORKVAT is to provide accurate students work within his or her Budget. We provide Ten-day warranty for students to check and review their works and also request any changes. Any work done by WORKVAT is authentic and is also tested for originality in anti-plagiarism software. All our payments are done via PayPal.</p>
          </div>
        </div>
      </div>
    </section><br><br>
   
    
<!--     <section class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">Our Team</h2>
          </div>
        </div>
    
        <div class="row align-items-center block__69944">
    
          <div class="col-md-6">
            <img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">

            <h3>John Smith</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in
              dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel ad
              explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>
    
    
          <div class="col-md-6 order-md-2">
            <img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">


            <h3>Drew Anderson</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in
              dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel ad
              explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>
    
         
        </div>
    </section>
 -->
{% endblock%}

accounts/templates/activation.html
{% extends 'base2.html' %}
{% load static %}
{% block title %}
  | Activate
{% endblock %}
{% block front %}
	<div class="mb-5 text-center">
      <h1 class="text-white font-weight-bold">Update Account</h1>
      <p>Update Your account</p>
    </div>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-lg-6 offset-3">
        <div align="center">
          <h2>Enter your new password</h2>    
        </div>
      
      <form method="post" class="form-group">
        {% csrf_token %}
        <label>Create Password</label>
        <input type="password" name="password" class="form-control">
        <label>Confirm new password</label>
        <input type="password" name="password2" class="form-control"><br>
        <button type="submit" class="btn btn-primary"> save </button>
      </form>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/adminList.html
{% extends 'base.html'%}
{% load static %}

{% block front %}
{% endblock %}

{% block content %}
	    <section class="site-section">
      <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">109,234 Job Listed</h2>
          </div>
        </div>


        <div class="mb-5">
          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- <div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-1.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">Freelancer</span>
              <h2><a href="job-single.html">Dropbox Product Designer</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>Melbourn</h3>
              <span class="meta">Australia</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-2.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-warning px-2 py-1 mb-3">Full-time</span>
              <h2><a href="job-single.html">Creative Director in Intercom</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>London</h3>
              <span class="meta">United Kingdom</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- <div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-3.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-success px-2 py-1 mb-3">Part-time</span>
              <h2><a href="job-single.html">FullStack Developer in Shopify</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>London</h3>
              <span class="meta">United Kingdom</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>
          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- <div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-4.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">Freelancer</span>
              <h2><a href="job-single.html">Dropbox Product Designer</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>Melbourn</h3>
              <span class="meta">Australia</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-5.jpg' %}" alt="Image" class="img-fluid"></a>
            </div -->
            <div class="col-md-4">
              <span class="badge badge-warning px-2 py-1 mb-3">Full-time</span>
              <h2><a href="job-single.html">Creative Director in Intercom</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>London</h3>
              <span class="meta">United Kingdom</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
             <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
           <!--  <div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-4.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-success px-2 py-1 mb-3">Part-time</span>
              <h2><a href="job-single.html">FullStack Developer in Shopify</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>London</h3>
              <span class="meta">United Kingdom</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
               <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <!-- <div class="col-md-2">
              <a href="job-single.html"><img src="{% static 'images/featured-listing-3.jpg' %}" alt="Image" class="img-fluid"></a>
            </div> -->
            <div class="col-md-4">
              <span class="badge badge-success px-2 py-1 mb-3">Part-time</span>
              <h2><a href="job-single.html">FullStack Developer in Shopify</a> </h2>
              <p class="meta">Publisher: <strong>John Stewart</strong> In: <strong>Design</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>London</h3>
              <span class="meta">United Kingdom</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">$60k &mdash; $100k</strong>
            </div>
            <div class="col-md-2 text-md-right">
              <a href="{% url 'assignment:singleAssignment'%}"><button class="btn btn-secondary">More</button></a>
            </div>
          </div>
          
        </div>

        <div class="row pagination-wrap">

          <div class="col-md-6 text-center text-md-left">
            <div class="custom-pagination ml-auto">
              <a href="#" class="prev">Previous</a>
              <div class="d-inline-block">
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
              </div>
              <a href="#" class="next">Next</a>
            </div>
          </div>
        </div>

      </div>
    </section>
{% endblock%}

accounts/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>

    <title>Workvat |  {% block title %} {% endblock %}</title>
    {% block description %}
      <meta name="description" content="Welcome to workvat">
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
  <body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
  
    <!-- NAVBAR -->


   {% block content %}
   {% endblock %}

  
  </div>

    <!-- SCRIPTS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/stickyfill.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    
    <script src="{% static 'js/custom.js' %}"></script>

     
  </body>
</html>

accounts/templates/confirm_email.html
{% extends 'base2.html' %}
{% block title %}
  Confirm email
{% endblock %}
{% block content %}
<br><br>
	<div class="container">
		<div class="row">
			<div class="jumbotron">
			  <h1 class="display-4">Hello</h1>
			  <p class="lead">We have sent a verification to you email address. Verify your email and complete the sign up. Thank you</p>
			  <hr class="my-4">
			  <p></p>
			  <p class="lead">
			    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
			  </p>
			</div>
	
	</div>
{% endblock %}

accounts/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  | Contact us
{% endblock %}

{% block front %}
   <div class="mb-5 text-center">
      <h1 class="text-white font-weight-bold">Contact Us</h1>
      <!-- <p>Find your dream jobs in our powerful career website template.</p> -->
    </div>
{% endblock %}

{% block content %}
    <section class="site-section" id="next-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            {% if send %}
            <div align="center">
              <h3 style="color: green;">Message Sent successful</h3>
            </div>
            {% endif%}
            <form action="" class="" method="post">
              {% csrf_token %}
              {% if not request.user.is_authenticated %}
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">First Name</label>
                  <input type="text" id="fname" class="form-control" name="firstName">
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Last Name</label>
                  <input type="text" id="lname" class="form-control" name="lastName">
                </div>
              </div>
    
              <div class="row form-group">
    
                <div class="col-md-12">
                  <label class="text-black" for="email">Email</label>
                  <input type="email" id="email" class="form-control" name="email">
                </div>
              </div>
              {% endif %}
              <div class="row form-group">
    
                <div class="col-md-12">
                  <label class="text-black" for="subject">Subject</label>
                  <input type="subject" id="subject" class="form-control" name="subject">
                </div>
              </div>
    
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="message">Message</label>
                  <textarea name="message" id="message" cols="30" rows="7" class="form-control"
                    placeholder="Write your notes or questions here..."></textarea>
                </div>
              </div>
    
              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary btn-md text-white">
                </div>
              </div>
    
    
            </form>
          </div>
          <div class="col-lg-5 ml-auto">
              <p class="mb-0 font-weight-bold">Chat on skype</p>
              <p class="mb-0">Id goes here</p>
              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">info@workvat.com</a></p>
              <p class="mb-0 font-weight-bold">Physical Address</p>
              <p class="mb-0"><a>Gateway House, Leicester LE1 9BH</a></p>
    
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock%}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  | Login
{% endblock %}

{% block front %}
   <div class="mb-5 text-center">
      <h1 class="text-white font-weight-bold">Login</h1>
      <!-- <p>Find your dream jobs in our powerful career website template.</p> -->
    </div>
{% endblock %}

{% block content %}
    <section class="site-section" id="next-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mb-5 mb-lg-0">
            <form action="" class="" method="post">
              {% csrf_token %}
        
              <div class="row form-group">
    
                <div class="col-md-12">
                  <label class="text-black" for="email" name="username">Email</label>
                  <input type="email" id="email" class="form-control" name="username">
                </div>
              </div>
   
              <div class="row form-group">
    
                <div class="col-md-12">
                  <label class="text-black" for="subject">Password</label>
                  <input type="password" id="subject" class="form-control" name="password">
                </div>
              </div>
    
    
              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Login" class="btn btn-primary btn-md text-white">
                </div>
              </div>
    
    
            </form>
            <a href="{% url 'password_reset'%}"><p>forget password?</p></a>
          </div>
        </div>
      </div>
    </section>

{% endblock%}

accounts/templates/password_change_done.html
{% extends 'base.html' %}
{% block title %}
  | Change Password
{% endblock %}
{% block content %}
<br><br>
	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-3" align="center">
				<h3>Your Password was changed successful</h3>
				
			</div>
		</div>
	</div>
	
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends 'base2.html' %}
{% block title %}
  | Reset Password
{% endblock %}
{% block content %}
	<br><br>
	<div class="container">
		<div class="row">
			<div class="jumbotron">
			  <h1 class="display-4">Hello</h1>
			  <p class="lead">Your Password was reset successful</p>
			  <hr class="my-4">
			  <p></p>
			  <p class="lead">
			    <a class="btn btn-primary btn-lg" href="{% url 'assignment:index' %}" role="button">Go back to site</a>
			  </p>
			</div>
	
	</div>
{% endblock %}