accounts/urls.py
from django.contrib import admin
from django.urls import path

from . views import (
    login_user,
    logout_user,

    about,
    contact,
    adminList,

    signup,
    activate
    )
app_name = "accounts"

urlpatterns = [
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),

    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('adminList/', adminList, name="adminList"),

     path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),

] 

assignment/urls.py
from django.contrib import admin
from django.urls import path
from django_downloadview import ObjectDownloadView
from . views import (
	index,
    addAssignment,
    updateAssignment,
    deleteAssignment,

    userAssignments,
    adminAssignments,

    accept,
    completed,
    counter,
    services,
    singleAssignment,

    assignmentChange,
    changes,
	)
from . models import UserAssignment, AssignmentMedia

download = ObjectDownloadView.as_view(model=UserAssignment, file_field='file')
downloadFinished = ObjectDownloadView.as_view(model=AssignmentMedia, file_field='file')
app_name = "assignment"

urlpatterns = [
    path('', index, name="index"),
    path('assignment/add/', addAssignment, name="addAssignment"),
    path('assignment/<int:assignment_id>/update/', updateAssignment, name="updateAssignment"),
    path('assignment/<int:assignment_id>/delete/', deleteAssignment, name="deleteAssignment"),

    path('assignments/', userAssignments, name="userAssignments"),
    path('assignments/admin/', adminAssignments, name="adminAssignments"),
    path('accept/<int:assignment_id>/', accept, name="accept"),
    path('completed/<int:assignment_id>/', completed, name="completed"),
    path('counter/', counter, name="counter"),

    path('services/', services, name="services"),
    path('assignment/<int:assignment_id>/', singleAssignment, name="singleAssignment"),

    path('assignment/change/', assignmentChange, name="assignmentChange"),
    path('changes/', changes, name="changes"),

    path('download/<int:pk>/', download, name="download_assignment"),
    path('downloadFinish/<int:pk>/', downloadFinished, name="downloadFinished"),
]

payment/urls.py
from django.contrib import admin
from django.urls import path

from . views import (
    payment_process,
    payment_done,
    payment_canceled,
    )
app_name = "payment"

urlpatterns = [
    path('payment_done/<int:assignmentId>/', payment_done, name="payment_done"),
    path('payment_canceled/<int:assignmentId>/', payment_canceled, name="payment_canceled"),
    path('payment_process/<int:assignment_id>/', payment_process, name="payment_process"),
   
] 

workvat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap

from assignment.sitemaps import StaticViewSitemap

sitemaps = {
    # 'product': ProductSitemap,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),

    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('', include("assignment.urls", namespace="assignment")),
    path('payment/', include("payment.urls", namespace="payment")),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change_form.html'), name="password_change"),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name="password_change_done"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),  name='password_reset_confirm'),
    path('password_reset_complete/', auth_views. PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

]

assignment/models.py
from django.db import models
from django.contrib.auth.models import User

from ckeditor.fields import RichTextField

class AssignmentType(models.Model):
	name = models.CharField(max_length=100)
	desc = models.TextField(blank=True, null=True)
	trend = models.BooleanField(default=False)

	averagePrice = models.FloatField(blank=True, null=True)

	def __str__(self):
		return self.name


class TypeDesc(models.Model):
	assignmentType 	= models.ForeignKey(AssignmentType, on_delete=models.CASCADE)

	name 			= models.CharField(max_length=50)
	desc 			= models.TextField()
	necessary 	 	= models.BooleanField(default=False)

	def __str__(self):
		return self.name + " " + self.assignmentType.__str__()

class UserAssignment(models.Model):
	user 			= models.ForeignKey(User, on_delete=models.CASCADE)
	assignmentType 	= models.ForeignKey(AssignmentType, on_delete=models.CASCADE)
	title 			= models.CharField(max_length=100, blank=True, null=True)
	citation 		= models.CharField(max_length=100, blank=True, null=True)
	font 			= models.CharField(max_length=100, default="Times New Roman")
	fontSize 		= models.FloatField(default=12.0)
	pages 			= models.FloatField(blank=True, null=True)
	
	expectedDate 	= models.DateField(auto_now_add=True, blank=True, null=True)
	dateRequested 	= models.DateTimeField(auto_now_add=True)
	dateCompleted 	= models.DateTimeField(blank=True,  null=True)

	desc 		 	= RichTextField(blank=True, null=True)
	file 			= models.FileField(blank=True, null=True)

	accepted 		= models.BooleanField(default= False)
	completed 		= models.BooleanField(default=False)

	is_sample 		= models.BooleanField(default=False)

	def __str__(self):
		return self.user.username + " " + self.assignmentType.__str__()

class AssignmentChange(models.Model):
	userAssignment 	= models.ForeignKey(UserAssignment, on_delete=models.CASCADE)
	title 			= models.CharField(max_length=100)
	desc 			= models.TextField() 
	done 			= models.BooleanField(default=False)

	def __str__(self):
		return self.title + " - " + self.userAssignment.__str__()

class AssignmentMedia(models.Model):
	userAssignment 	= models.OneToOneField(UserAssignment, on_delete=models.CASCADE)
	file 			= models.FileField(upload_to='assignments/')
	is_complete 	= models.BooleanField(default=False)

	def __str__(self):
		return self.userAssignment.__str__()

class Constraint(models.Model):
	assignmentType 	= models.ForeignKey(UserAssignment, on_delete=models.CASCADE, blank=True, null=True)
	name 			= models.CharField(max_length=100)
	desc 			= RichTextField()

	must 			= models.BooleanField(default=False)

	def __str__(self):
		return self.name + " - " + self.assignmentType.__str__()

assignment/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import UserAssignment

class UserAssignmentForm(forms.ModelForm):

    class Meta:
        model = UserAssignment
        fields = [
            # 'assignmentType',
            'desc',
            # 'file',
            # 'userPrice',
        ]

        # widgets = {
        #     "assignmentType":forms.Select(attrs={"class":"form-control"}),
        #     "desc":forms.Textarea(attrs={"class":"form-control"}),
        #     "file":forms.FileInput(attrs={"class":"form-control"}),
        #     "userPrice":forms.TextInput(attrs={"class":"form-control"}),
        # }
        # 

assignment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from accounts.models import Testimonial
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.urls import reverse
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt

from payment.models import AssignmentPayment

from . forms import UserAssignmentForm
from . models import (
	AssignmentChange,
	AssignmentMedia,
	AssignmentType,
	TypeDesc,
	UserAssignment,
	)


def index(request):
	template_name = "./index.html"
	users = User.objects.count()
	assignmentsCount = UserAssignment.objects.count()
	assignments = UserAssignment.objects.filter(is_sample=True)
	completedAssignmentsCount = UserAssignment.objects.filter(completed=True).count()
	testimonials = Testimonial.objects.all()
	userAv = request.session.get("userAv")
	request.session["userAv"] = False
	context = {
			 "users":users,
			 "assignments":assignments,
			 "assignmentsCount":assignmentsCount, 
			 "completedAssignmentsCount":completedAssignmentsCount,
			 'testimonials':testimonials,
			 "userAv":userAv
			 }
	return render(request, template_name, context)

def services(request):
	template_name = "./services.html"
	servicesIn = AssignmentType.objects.all()
	testimonials = Testimonial.objects.all()
	page = request.GET.get('page', 1)

	paginator = Paginator(servicesIn, 12)
	try:
		services = paginator.page(page)
	except PageNotAnInteger:
		services = paginator.page(1)
	except EmptyPage:
		services = paginator.page(paginator.num_pages)
	context = {"services":services, "testimonials":testimonials}
	return render(request, template_name, context)

@login_required
def singleAssignment(request, assignment_id):
	template_name = "./singleAssignment.html"
	assignment = UserAssignment.objects.get(pk=assignment_id)
	host = request.get_host()
	total = assignment.assignmentpayment.userPrice * assignment.pages
	paypal_dict = {
		'business': settings.PAYPAL_RECEIVER_EMAIL,
		# 'amount': '%.2f' % total,
		'amount': '0.3',
		'item_name': 'Order {}'.format(assignment_id),
		'invoice' : str(assignment_id),
		'currency_code': 'USD',
		'notify_url':'http://{}{}'.format(host, reverse('paypal-ipn')),
		'return_url': 'http://{}{}'.format(host, reverse('payment:payment_done', kwargs={'assignmentId':assignment_id})),
		'cancel_return':'http://{}{}'.format(host, reverse('payment:payment_canceled', kwargs={'assignmentId':assignment_id})),
	}
	form = PayPalPaymentsForm(initial=paypal_dict)

	if request.method == "POST":
		file = request.FILES.get("file")
		try:
			media = assignment.assignmentmedia
			media.file = file
			media.save()
		except:
			assignmentMedia = AssignmentMedia(userAssignment=assignment, file=file)
			assignmentMedia.save()
		assignment.completed = True
		assignment.save()

	context = {"assignment":assignment, 'form':form}
	return render(request, template_name, context)

@login_required
def addAssignment(request):
	template_name = "./addAssignment.html"
	assignmentsTypes = AssignmentType.objects.all()
	if request.method == "POST":
		form = UserAssignmentForm(request.POST)
		if form.is_valid():
			desc = form.cleaned_data['desc']
		assignmentTypeId = int(request.POST.get("assignmentType"))
		assignmentType = assignmentsTypes.get(pk=assignmentTypeId)
		title = request.POST.get("title")
		# desc = request.POST.get("desc")
		expectedDate = request.POST.get("expectedDate")
		userPrice = int(request.POST.get("userPrice"))
		citation = request.POST.get("citation")
		fontType = request.POST.get("fontType")
		fontSize = float(request.POST.get("fontSize"))
		currency = request.POST.get("currency")
		file = request.FILES.get("file")
		pages = request.POST.get("pages", None)
		assignment = UserAssignment(
			user=request.user,
			assignmentType=assignmentType,
			title=title,
			desc=desc,
			expectedDate=expectedDate,
			citation=citation,
			font=fontType,
			fontSize=fontSize,
			pages = pages,
			)
		assignment.save()
		if file:
			assignment.file = file
			assignment.save()
		assignmentPay = AssignmentPayment(userAssignment=assignment, userPrice=userPrice, currency=currency)
		assignmentPay.save()
		return redirect("assignment:singleAssignment", assignment_id = assignment.id)
	else:
		form = UserAssignmentForm()

	context = {"assignmentsTypes":assignmentsTypes, "form":form}
	return render(request, template_name, context)

@login_required
def updateAssignment(request, assignment_id):

	template_name = "./update.html"
	assignmentsTypes = AssignmentType.objects.all()
	assignmentIn = UserAssignment.objects.get(pk=assignment_id)
	if request.method == "POST":
		form = UserAssignmentForm(request.POST, instance=assignmentIn)
		if form.is_valid():
			desc = form.cleaned_data['desc']
		assignmentTypeId = int(request.POST.get("assignmentType"))
		assignmentType = assignmentsTypes.get(pk=assignmentTypeId)
		title = request.POST.get("title")
		# desc = request.POST.get("desc")
		expectedDate = request.POST.get("expectedDate")
		userPrice = float(request.POST.get("userPrice"))
		citation = request.POST.get("citation")
		fontType = request.POST.get("fontType")
		fontSize = float(request.POST.get("fontSize"))
		currency = request.POST.get("currency")
		file = request.FILES.get("file", None)
		assignmentIn.assignmentType = assignmentType
		assignmentIn.user = request.user
		assignmentIn.title = title
		assignmentIn.expectedDate = expectedDate
		assignmentIn.assignmentpayment.userPrice = userPrice
		assignmentIn.assignmentpayment.currency = currency
		assignmentIn.citation = citation
		assignmentIn.font = fontType
		assignmentIn.fontSize = fontSize
		if file:
			assignmentIn.file = file
		assignmentIn.save()
		assignmentIn.assignmentpayment.save()
	
		return redirect("assignment:singleAssignment", assignment_id = assignmentIn.id)
	else:
		form = UserAssignmentForm(instance=assignmentIn)

	context = {"assignmentsTypes":assignmentsTypes, "form":form, 'assignment':assignmentIn}
	return render(request, template_name, context)

@login_required
def deleteAssignment(request, assignment_id):
	assignment = UserAssignment.objects.get(pk=assignment_id)
	assignment.delete()
	url = request.META.get('HTTP_REFERER')
	return redirect("assignment:userAssignments")

@login_required
def userAssignments(request):
	template_name = "./userAssignments.html"
	userAssignmentsIn = request.user.userassignment_set.all().order_by("-pk")
	assignment = None
	if request.method == "POST":
		assignment_id = int(request.POST.get("id"))
		assignment = userAssignmentsIn.get(pk=assignment_id)

	page = request.GET.get('page', 1)

	paginator = Paginator(userAssignmentsIn, 10)
	try:
		assignments = paginator.page(page)
	except PageNotAnInteger:
		assignments = paginator.page(1)
	except EmptyPage:
		assignments = paginator.page(paginator.num_pages)
	context = {"assignments":assignments, "assignment":assignment}
	return render(request, template_name, context)

@login_required
def adminAssignments(request):
	template_name = "./adminAssignments.html"
	assignmentsList = UserAssignment.objects.all().order_by("-expectedDate")
	assignment = None
	if request.method == "POST":
		assignment_id = int(request.POST.get("id"))
		assignment = assignmentsList.get(pk=assignment_id)
	page = request.GET.get('page', 1)

	paginator = Paginator(assignmentsList, 10)
	try:
		assignments = paginator.page(page)
	except PageNotAnInteger:
		assignments = paginator.page(1)
	except EmptyPage:
		assignments = paginator.page(paginator.num_pages)
	context = {"assignments": assignments}
	return render(request, template_name, context)

@login_required
def accept(request, assignment_id):
	assignment = UserAssignment.objects.get(pk=assignment_id)
	assignment.accepted = not assignment.accepted
	assignment.save()
	url = request.META.get('HTTP_REFERER')
	return redirect(url)

@login_required
def completed(request, assignment_id):
	assignment = UserAssignment.objects.get(pk=assignment_id)
	assignment.completed = not assignment.completed
	if assignment.completed == True:
		assignment.dateCompleted = timezone.now() 
	assignment.save()
	url = request.META.get('HTTP_REFERER')
	return redirect(url)


@login_required
def counter(request):
	assignment_id = int(request.POST.get("id"))
	counterPrice = int(request.POST.get("counterPrice"))
	assignment = UserAssignment.objects.get(pk=assignment_id)
	assignment.counterPrice = counterPrice
	assignment.save()
	url = request.META.get('HTTP_REFERER')
	return redirect(url)

@login_required
def assignmentChange(request):
	if request.method == "POST":
		title = request.POST.get('title')
		desc = request.POST.get('desc')
		assignment_id = int(request.POST.get('id'))
		assignment = get_object_or_404(UserAssignment, pk=assignment_id)
		if assignment.assignmentchange_set.count() < 2:
			assignmentChangeIn = AssignmentChange(userAssignment=assignment, title=title, desc=desc)
			assignmentChangeIn.save()
		elif assignment.assignmentchange_set.count() == 2:
			assignmentChangeIn = AssignmentChange(userAssignment=assignment, title=title, desc=desc, done=True)
			assignmentChangeIn.save()
		assignment.completed = False
		assignment.save()
	return redirect("assignment:singleAssignment", assignment_id=assignment.id)


@login_required
def changes(request):
	template_name = "./changes.html"
	assignments = UserAssignment.objects.all().order_by("expectedDate")
	context = {"assignments":assignments}
	return render(request, template_name, context)

assignment/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>

    <title>Workvat {% block title %} {% endblock %}</title>
    {% block description %}
      <meta name="description" content="Welcome to workvat">
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
  <body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    

    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="site-logo col-6"><a href="{% url 'assignment:index' %}">Workvat <img src="{% static 'images/logo.jpeg'%}" width="20" height="20"></a></div>

          <nav class="mx-auto site-navigation">
            <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
              <li><a href="{% url 'assignment:index' %}" class="nav-link active">Home</a></li>
              {% if request.user.is_authenticated%}
                <li><a href="{% url 'assignment:userAssignments'%}">My jobs</a></li>
              {% else %}
                <li><a data-toggle="modal" data-target="#exampleModalCenter">My jobs</a></li>
              {%endif%}
              
              <li><a href="{% url 'accounts:about' %}">About</a></li>
              <li><a href="{% url 'assignment:services'%}">Services</a></li>
              <!-- <li><a href="blog.html">Blog</a></li> -->
              {% if request.user.is_authenticated%}
              <li><a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-primary">
              Logout
            </button></a></li>
            <!--  <li><a href="#">
              Change Password</a></li> -->
            {% else %}
               <li><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
              Login
            </button></li>
            {% endif%}
            {% if request.user.is_superuser%}
               <li><a href="{% url 'assignment:adminAssignments' %}"><button type="button" class="btn btn-warning">
              Jobs
            </button></a></li>
            {% endif%}
            </ul>
          </nav>
          <!-- modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <div align="center">
                   <!-- <h5 class="modal-title" id="exampleModalCenterTitle">Login</h5> -->
                </div>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                   <div align="center">
                   <h3 class="modal-title" id="exampleModalCenterTitle">Login</h3>
                </div>
                  <form action="{% url 'accounts:login'%}" method="post" class="form-group">
                    {% csrf_token %}
                    <label>Email</label>
                    <input type="email" name="username" class="form-control" placeholder="example@mail.com" required><br>
                   
                    <label>Password</label>
                    <input type="password" name="password" placeholder="Password" class="form-control" required><br>
                     <div align="center">
                      <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                      <button type="submit" class="btn btn-primary">Login</button><br>
                      <a href="{% url 'password_reset' %}">forgot password?</a> or
                       <a href="{% url 'assignment:index' %}">create account</a>
                    </div>
                </div>
               
                </form>
                
              </div>
            </div>
          </div>
          <!-- modal -->
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto">
              <a href="{% url 'accounts:contact'%}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-paper-plane"></span>Contact Us</a>
              {% if request.user.is_authenticated %}
                <a href="{% url 'password_change'%}" class="btn btn-primary border-width-2 d-none d-lg-inline-block">Change Password</a>  
              {% endif %}
            </div>

            <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
          </div>

        </div>
      </div>
    </header>
        <section class="home-section section-hero inner-page overlay bg-image"
      style="background-image: url('../../static/images/hero_1.jpg');" id="home-section">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
          	{% block front %}
         <!--    <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">Contact Us</h1>
              <p>Find your dream jobs in our powerful career website template.</p>
            </div> -->
            {% endblock %}
          </div>
        </div>
      </div>
    </section>

   {% block content %}
   {% endblock %}
    
    <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('../../static/images/hero_1.jpg');">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8">
            {% if request.user.is_authenticated %}
            <h2 class="text-white">Find experience Freelancers</h2>
            <!-- <p class="mb-0 text-white lead">You state your price remember!!</p> -->
            {% else %}
             <h2 class="text-white">Find experience Freelancers</h2>
            <!-- <p class="mb-0 text-white lead">Workvart is your best choice</p> -->
            {% endif%}
          </div>
          <div class="col-md-3 ml-auto">
            {% if request.user.is_authenticated %}
             <a href="{% url 'assignment:addAssignment' %}" class="btn btn-warning btn-block btn-lg">Post a job</a>
            {% else %}
              <a href="{% url 'assignment:index' %}" class="btn btn-warning btn-block btn-lg">Sign Up</a>
            {% endif%}
          </div>
        </div>
      </div>
    </section>
    
    
    <footer class="site-footer">

      
      <div class="container">
        <div class="row mb-5">
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Search Trending</h3>
            <ul class="list-unstyled">
              {% for assignmentType in assignmentTypes%}
              <li><a href="#"> {{assignmentType.name}}</a></li>
              {% endfor %}
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Company</h3>
            <ul class="list-unstyled">
              <li><a href="{% url 'accounts:about'%}">About Us</a></li>
              <!-- <li><a href="{% url 'assignment:index'%}#sample_work">Sample Work</a></li> -->
              <!-- <li><a href="#">Blog</a></li>
              <li><a href="#">Resources</a></li> -->
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Support</h3>
            <ul class="list-unstyled">
              <li><a href="mail-to:hashimathman@gmail.com">Support</a></li>
              <li><a href="#">Privacy</a></li>
              <li><a href="#">Terms of Service</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Contact Us</h3>
            <div class="footer-social">
              <a href="https://www.facebook.com/Workvat-103761421038326/?modal=admin_todo_tour" target="_blank"><span class="icon-facebook"></span></a>
              <a href="https://twitter.com/workvat" target="_blank"><span class="icon-twitter"></span></a>
              <a href="https://www.instagram.com/work_vat/" target="_blank"><span class="icon-instagram"></span></a>
              <a href="https://www.linkedin.com/in/workvat-online-700898195" target="_blank"><span class="icon-linkedin"></span></a>
            </div>
          </div>
        </div>

       
      </div>
       <div align="center">
        <p>Copyright @2019 - All Rights Reserved. Privacy Policy | Site Terms & Disclosures.Hosted by <a href="{% url 'assignment:index' %}" style="color: lightblue;">workvat.com</a></p>
      </div>
    </footer>
  </div>

    <!-- SCRIPTS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/stickyfill.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    
    <script src="{% static 'js/custom.js' %}"></script>

     
  </body>
</html>

assignment/templates/updateAssignment.html
{% extends 'base.html'%}
{% load static%}